I am learning pytest, and am seeing how pytest can handle various exceptions
